analize_site_ir/urls.py
from django.contrib import admin , auth
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import auth_login, auth_logout


urlpatterns = [
    path('admin/', admin.site.urls, name=admin),
    path('', include('site_app.urls')),
    path('back_test', include('back_test_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document__root=settings.STATIC_ROOT)

urlpatterns += [path('accounts/', include('django.contrib.auth.urls'))]

back_test_app/urls.py
from django.urls import path
from . import views

app_name = 'back_test_app'

urlpatterns = [
    path('', views.back_test, name='back_test'),
    path('/recent_result/', views.recent_result, name='recent_result'),
]

site_app/urls.py
from django.urls import path
from . import views

app_name = 'site_app'

urlpatterns = [
    path('', views.index, name='index'),
]

site_app/models.py
from django.db import models

# Create your models here.

site_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'site_app/index.html')

site_app/templates/site_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}analize site{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'site_app/css/styles.css' %}">
</head>

<body>

    <div class="container-fluid">

        <div class="row">
            <div class="menu" style="padding: 10px;">
                <div class="col-sm-2" >
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}?next={{request.path}}">logout</a>
                    {% else %}
                        <a href="{% url 'login' %}?next={{request.path}}">login</a>
                    {% endif %}
                </div>

                <div class="col-sm-2">
                    {% if user.is_authenticated %}
                        <P>welcome {{ user.first_name }} ( {{ user.username }} )</P>
                    {% endif %}
                </div>
                <div class="col-sm-6"></div>
                <div class="col-sm-2">
                    <p class="float-right">my site</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 sidebar">
                {% block sidebar %}
                    <ul class="sidebar-nav">

                        <li><a href="{% url 'site_app:index' %}">Home</a></li>
                        <li><a href="{% url 'back_test_app:back_test' %}">back test</a></li>
                        <li><a href="{% url 'back_test_app:recent_result' %}">view back test result</a></li>
                        <li><a href="/admin/">admin page</a></li>

                        {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}?next={{request.path}}">logout</a></li>
                        {% else %}
                            <li><a href="{% url 'login' %}?next={{request.path}}">login</a></li>
                        {% endif %}
                    </ul>
                {% endblock %}
            </div>
                <div class="col-sm-10 ">
                <div class="row">
                    {% block message %}{% endblock %}
                </div>
                <div class="row">
                    {% block content %}{% endblock %}
                </div>

            </div>
        </div>

    </div>
</body>
</html>

site_app/templates/site_app/index.html
{% extends "site_app/base.html" %}
{% block title %}
    index
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <P>welcome {{ user.first_name }}</P>
        <P><a href="{% url 'back_test_app:back_test' %}">back test</a></P>
        <P><a href="{% url 'back_test_app:recent_result' %}">view recent result</a></P>
    {% else %}
        <h3>for use site you need login</h3>
        <P><a href="{% url 'login' %}">login</a></P>
    {% endif %}
{% endblock %}